# Generated by Django 6.0.2 on 2026-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
