# Generated by Django 6.0.3 on 2026-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
